# Generated by Django 5.0.2 on 2024-03-03 11:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lib_manage', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=10, null=True)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='lib_manage.books')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='lib_manage.member')),
            ],
        ),
    ]
