# Generated by Django 5.0.2 on 2024-03-03 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lib_manage', '0004_alter_books_author_alter_books_publisher_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books',
            name='holder',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
