# Generated by Django 5.0.2 on 2024-03-03 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lib_manage', '0005_alter_books_holder'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books',
            name='holder',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='member',
            name='fees',
            field=models.IntegerField(default=0),
        ),
    ]
